using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Point1
{
    public class KarttaData
    {
        public string p;
        public string p2;

       public KarttaData()
        {
            //012345678901234567890123456789
            p = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";//0
            p += "XVVVVVVVOOOOOOOOOOOOOOOOZOOOOX";//1
            p += "XXOOOOOOOOOOOOOOOOOOOOOOOOOOOX";//2
            p += "XXOOOOOOOOOOOOOOOOOOOOOOOOOOOX";//3
            p += "XXOOOOOOOOOOOOOOOOOOOOOOOOOOOX";//4
            p += "XXOOOOOOOOOOOOOOOOOOOOOOOOOOOX";//5
            p += "XXOOOOOOOOOOOOOOOOOOOOOOOOOOOX";//6
            p += "XXOOOOOOOOOOOOOOOOOOOOOOOOOOOX";//7
            p += "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX";//8
            p += "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX";//9
            p += "XOXOOOOOOOOOOOOOOOOOOOOOOOOOOX";//10
            p += "XOXOOOOOOOOOOOOOOOOOOOOOOOOOOX";//11
            p += "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX";//12
            p += "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX";//13
            p += "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX";//14
            p += "XOOZZZOOXXXXXXXXXXXOOOOOOOOOZX";//15
            p += "XOOZZZOOXOOOOOOOOOOOOOOOOOZOOX";//16
            p += "XOOZZOOOXOOOOOOOOOOOOOOOOZOOOX";//17
            p += "XOOZZOOOXOOOOOOXXOOOXXXXXXXXXX";//18
            p += "XOOZOOOOXOOOOOOXXOOOOOVOOOOOOX";//19
            p += "XOOZOOOOOOOOOOOXXOOOOOOOOOOOOX";//20
            p += "XOOZOOOOOOOOOOOXXXXXXXXXXXOOOX";//21
            p += "XOOOZOOOOOOOOOOOOOOOOOOOOOOOOX";//22
            p += "XOOOOZOOOOOOOOOOOOOOOOZZZOOOOX";//23
            p += "XOOXXXXXXXXOOOOOOOVOZZZZZOOOOX";//24
            p += "XOOOOOOOOOOOXOOOOOOZZZZZZOOOOX";//25
            p += "XOOOOOOOOOOOOOOOOOOOOZZZZOOOOX";//26
            p += "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX";//27
            p += "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX";//28
            p += "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";//29
            p += "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";//30

            //012345678901234567890123456789
            p2 = "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO";//0
            p2 += "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO";//1
            p2 += "OOOOOOOOOOOOOOOOOAOOOOOOOOOOOO";//2
            p2 += "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO";//3
            p2 += "OOOOOOOOOOOAAAAAOOOOOOOOOOOOOO";//4
            p2 += "OOOOOOOOOOOAAAAAOOOOOOOOOOOOOO";//5
            p2 += "OOOOOOOOOOOOOOOOOOAOOOOOOOOOOO";//6
            p2 += "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO";//7
            p2 += "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX";//8
            p2 += "XOOOOOOOOOOOAOOOOOAOOOOOOOOOOX";//9
            p2 += "XOXOOOOOOOOOOOOOOOOOOOOOOOOOOX";//10
            p2 += "XOXOOOOOOOOOOOOOOOOOOOOOOOOOOX";//11
            p2 += "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX";//12
            p2 += "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX";//13
            p2 += "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX";//14
            p2 += "XOOZZZOOXXXXXXXXXXXOOOOOOOOOZX";//15
            p2 += "XOOZZZOOXOOOOOOOOOOOOOOOOOZOOX";//16
            p2 += "XOOZZOOOXOOOOOOOOOOOOOOOOZOOOX";//17
            p2 += "XOOZZOOOXOOOOOOXXOOOXXXXXXXXXX";//18
            p2 += "XOOZOOOOXOOOOOOXXOOOOOVOOOOOOX";//19
            p2 += "XOOZOOOOOOOOOOOXXOOOOOOOOOOOOX";//20
            p2 += "XOOZOOOOOOOOOOOXXXXXXXXXXXOOOX";//21
            p2 += "XOOOZOOOOOOOOOOOOOOOOOOOOOOOOX";//22
            p2 += "XOOOOZOOOOOOOOOOOOOOOOZZZOOOOX";//23
            p2 += "XOOXXXXXXXXOOOOOOOVOZZZZZOOOOX";//24
            p2 += "XOOOOOOOOOOOXOOOOOOZZZZZZOOOOX";//25
            p2 += "XOOOOOOOOOOOOOOOOOOOOZZZZOOOOX";//26
            p2 += "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX";//27
            p2 += "XOOOOOOOOOOOOOOOOOOOOOOOOOOOOX";//28
            p2 += "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";//29
            p2 += "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";//30
        }
    }
}
